[[headers]]
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self';"

  cache-control = '''
  max-age=0,
  no-cache,
  no-store,
  must-revalidate'''