[[headers]]
  for = "/*"
    [headers.values]
    cache-control = "max-age=0, no-cache, no-store, must-revalidate"
    content-security-policy = '''
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval';
      style-src 'self' 'unsafe-inline';
      img-src * data:;
      font-src 'self' data:;
      object-src 'none'
    '''
