[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    Content-Security-Policy = "default-src 'self' https://concertify.netlify.app; img-src 'self' data: https://storage.googleapis.com; script-src 'self' 'unsafe-inline' 'unsafe-eval'; font-src 'self' https://fonts.googleapis.com; style-src 'self' 'unsafe-inline'"
    X-Content-Type-Options = "nosniff"
    Permissions-Policy = "camera=(); battery=(self); geolocation=(); microphone=('https://a-domain.com')"
    Referrer-Policy = "origin-when-cross-origin"
