import "./globals.css";
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import Nav from "@/app/components/nav/page";
import {hasCookie} from "@/helpers/cookieHelper";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
    const showComponent = hasCookie("token");

    return (
        <html lang="en">
            <body className={inter.className}>
                {showComponent ? (
                    // Render your component here
                    <Nav />
                ) : (
                    // Render something else or nothing
                    "you're not logged in"
                )}
                <main>{children}</main>
            </body>
        </html>
    );
}
